version: '3'

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  discord-stt:
    image: discord-stt
    env_file:
      - .env
    networks:
      - postgres-network
    depends_on:
      - database

networks: 
  postgres-network:
    driver: bridge
